- name: set prompt name
  ansible.builtin.shell: set-prompt elk

- name: copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed



