- name: set prompt name
  ansible.builtin.shell: set-prompt elk

- name: copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: Start elasticsearch
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: true
    daemon_reload: true

- name: install Kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: start kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: true

- name: Update server port
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^server.port: 5601'
    line: "server.port: 5601"

- name: Update server host
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "^server.host: localhost"
    line: "server.host: 0.0.0.0"

- name: Start Kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted
