format_version: 10
pipelines:
  terraform-tf-apply:
    group: Tools
    materials:
      git-da613e5:
        git: https://github.com/sh-devops-i1/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: { command: terraform, arguments: [ "init",], run_if: passed }
                - exec: { command: terraform, arguments: [ "apply", "-auto-approve" ], run_if: passed }
